version: '3.9'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  keycloak:
    image: jboss/keycloak
    restart: always
    ports:
      - "8888:8080"
    environment:
      - KEYCLOAK_USER=root
      - KEYCLOAK_PASSWORD=root
    networks:
      - auth-network
    
networks:
  auth-network:
    driver: bridge