version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    restart: always
    ports:
      - "8888:8080"
    environment:
      - KEYCLOAK_USER=root
      - KEYCLOAK_PASSWORD=root
      - PROXY_ADDRESS_FORWARDING=true